-- 코드를 작성해주세요
SELECT ID, GENOTYPE, (SELECT D3.GENOTYPE FROM ECOLI_DATA D3 WHERE D3.ID = D1.PARENT_ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA D1
WHERE (D1.GENOTYPE & (SELECT D2.GENOTYPE FROM ECOLI_DATA D2 WHERE D2.ID = D1.PARENT_ID)) = (SELECT D2.GENOTYPE FROM ECOLI_DATA D2 WHERE D2.ID = D1.PARENT_ID)